spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springcourse
    username: postgres
    password: .postgres

flyway:
  url: jdbc:postgresql://localhost:5432/springcourse
  user: postgres
  password: .postgres
  enabled: true
  locations:
    - 'classpath:db/migration'
